### ISSUE TITLE
Need help and support new devices

### ISSUE THREAD

**Issue by awed730** [Lekensteyn/lglaf#33]
I'm using WIN10 32bit And I have LG Ls755 MTK based Devices with CPU MT6755
when i put the device in download mod and make the command 
`python lglaf.py --skip-hello --debug` 
it's show that the device isn't found or need to download LGusb driver.
but i was able to flash stock firmware with CM2 dongle and thats means the driver installed correctly
`python lglaf.py --skip-hello --debug
LAF Crypto failed to import!
LGLAF.py: DEBUG: Using serial port: None
Traceback (most recent call last):
  File "lglaf.py", line 505, in <module>
    main()
  File "lglaf.py", line 478, in main
    comm = autodetect_device()
  File "lglaf.py", line 404, in autodetect_device
    raise RuntimeError("Device not found, try installing LG drivers")
RuntimeError: Device not found, try installing LG drivers`.
.
.
@Lekensteyn

**Comment by Lekensteyn** [comment]
Hi, is it possible to provide boot Linux, run the command:

    lsusb > lsusb.txt
    sudo lsusb -v -d 1004: > lsusb2.txt

and attach the two files?

**Comment by tuxuser** [comment]
@awed730 What's a `CM2 dongle`?

**Comment by steadfasterX** [comment]
CM2 dongle -> flashing software for SIM unlock, partition flashing etc made by [infinity box](https://www.infinity-box.com/)

**Comment by shinobisoft** [comment]
I think the MTK chipset is the issue. Linux is not detecting my X Power either. It does have a LAF partition however... I just bought a Stylo 3, but haven't had a chance to see if this tool works with it or not...

**Comment by tuxuser** [comment]
It could be wrong but here's my story (for windows):
Initially I had the error about missing driver too.. But Device Manager showed a serial and MTP device... LG Mobile support tool detected the device too (and installed drivers on its own).. So I wondered why it didn't work.

Apparently I had to install the full LG Driver pack (a recent version, the one in the README is outdated) and it finally worked.

**Comment by Lekensteyn** [comment]
@shinobisoft the first lsusb output shows the LAF interface at endpoint 3 and 2. Do you have the same problem as OP, not being able to use the tool? Or is it just a problem on Windows?
(Aside from this issue, you supplied some files before, I can't remember if you confirmed it working, does the support-ls996 branch work for your LS996 model? If so, should I merge it back to master then?)

@tuxuser if a different LG driver is needed on Windows, feel free to open a PR to mention it. (The current link in the README looks dead to me?) Note the original post is about Windows 10, not Linux.

**Comment by shinobisoft** [comment]
@Lekensteyn Yes, the LS996 branch is working just fine. I did confirm that via email. Haven't had a chance to test anything for the LS755 yet.

**Comment by shinobisoft** [comment]
@Lekensteyn After a quick test, lglaf.py DOES in fact communicate with the LS755 X Power under Linux/Ubuntu 16.04. The device is running Marshmallow. Tried a few shell commands like "ls, id, getenforce" and every response was "Hello, I am LAF. Nice to meet you."... 

Sending the CTRL command works. Well "CTRL POFF" specifically. I currently don't have a lot of free time but I'll do some more thorough testing as soon as I get a chance.

**Comment by awed730** [comment]
Everyone here ..Thank you very very much for trying to belp me.
Like i said before
I'm using windows and i'm not a Linux user
If it's not detecting by the lglaf i'll try to install a new LG usb driver ..
And everyone if you need in somehow to try something on LS755 i'm ready to let you try what ever you want via team viewer or what you preferred to use it.
I have the Device and it's my plasure to let you do your things.. Even the device will going dead LoL.
If we excess of making LGLAF work with LS755 it wil be a perfect Achievement and good work not for me but for other who using LG X POWER LS755

**Comment by steadfasterX** [comment]
@awed730 For exact this reason [FWUL ](http://tinyurl.com/FWULatXDA) exists just give it a try and check if you can communicate with your device by opening the LG folder from the desktop and doubleclick on LGlaf icon there
