### ISSUE TITLE
Problem with communication port 

### ISSUE THREAD

**Issue by malekaltanani** [Lekensteyn/lglaf#46]
Problem with communication port in windows7

Traceback (most recent call last):
  File "C:\lglaf\lglaf.py", line 504, in <module>
    main()
  File "C:\lglaf\lglaf.py", line 477, in main
    comm = autodetect_device()
  File "C:\lglaf\lglaf.py", line 404, in autodetect_device
    return FileCommunication(serial_path)
  File "C:\lglaf\lglaf.py", line 259, in __init__
    self.f = open(file_path, 'r+b')
IOError: [Errno 2] No such file or directory: u'COM11'

**Comment by malekaltanani** [comment]
IOError: [Errno 2] Could not find file 'C:\lglaf\COM16'.: COM16
