### ISSUE TITLE
LGLAF permission denied - LG K10 (2017)

### ISSUE THREAD

**Issue by DaniloColazo** [Lekensteyn/lglaf#58]
Hello guys, i have a problem with LG K10 (2017). The screen is broken and no adb enable and i need extract some data. When i try to execute the command python lglaf.py --cr --debug --rawshell give me this result

Traceback (most recent call last):
  File "lglaf.py", line 510, in <module>
    main()
  File "lglaf.py", line 483, in main
    comm = autodetect_device()
  File "lglaf.py", line 414, in autodetect_device
    return USBCommunication()
  File "lglaf.py", line 287, in __init__
    current_cfg = self.usbdev.get_active_configuration()
  File "/home/danilo/.local/lib/python2.7/site-packages/usb/core.py", line 875, in get_active_configuration
    return self._ctx.get_active_configuration(self)
  File "/home/danilo/.local/lib/python2.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/home/danilo/.local/lib/python2.7/site-packages/usb/core.py", line 236, in get_active_configuration
    self.managed_open()
  File "/home/danilo/.local/lib/python2.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/home/danilo/.local/lib/python2.7/site-packages/usb/core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/home/danilo/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "/home/danilo/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/home/danilo/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

Any help, the mobile need to be root? Sorry for my english

**Comment by steadfasterX** [comment]
sudo python......
