### ISSUE TITLE
PyUSB is not detected

### ISSUE THREAD

**Issue by CrimsonFork** [Lekensteyn/lglaf#68]
I installed all dependencies, but launching `lglaf.py` puts out:
```
user@laptop:~/Downloads/software/flashing/lglaf-master$ python lglaf.py
No handlers could be found for logger "LGLAF.py"
Traceback (most recent call last):
  File "lglaf.py", line 510, in <module>
    main()
  File "lglaf.py", line 483, in main
    comm = autodetect_device()
  File "lglaf.py", line 413, in autodetect_device
    raise RuntimeError("Please install PyUSB for USB support")
RuntimeError: Please install PyUSB for USB support
```
```
user@laptop:~/Downloads/software/flashing/lglaf-master$ pip3 install PyUSB
Requirement already satisfied: PyUSB in /home/user/.local/lib/python3.8/site-packages (1.0.2)
```
I'm trying to revive a borked LG G3 (d855) that worked for about 15 minutes until I decided to toggle encryption before restoring TWRP.

**Comment by whew-inc** [comment]
Did you figure out a solution?

**Comment by CrimsonFork** [comment]
@whew-inc I don't remember, t'was a long time ago. I think I didn't, but a faint imprint of a memory suggests restarting and looking for running services which may conflict.
